export const AUDIT_ACTIONS = [
  "auth.register",
  "auth.login",
  "auth.password.change",
  "auth.password.reset",
  "question.create",
  "question.update",
  "question.delete",
  "question.status.change",
  "question.bulk-import",
  "question.bulk-review",
  "taxonomy.create",
  "taxonomy.update",
  "taxonomy.delete",
  "paper.create",
  "paper.update",
  "paper.delete",
  "paper.clone",
  "paper.publish",
  "paper.archive",
  "paper.restore",
  "paper.export",
  "user.update-role",
  "user.suspend",
  "organization.create",
  "organization.update",
  "organization.assign-owner",
  "organization.member.update-role",
  "organization.member.remove",
  "organization.invitation.send",
  "organization.invitation.accept",
  "organization.invitation.reject",
  "organization.invitation.cancel",
  "organization.team.create",
  "organization.team.update",
  "organization.team.delete",
  "security.csrf-rejected",
  "security.rate-limited",
] as const;

export type AuditAction = (typeof AUDIT_ACTIONS)[number];
